---
- name: Symlink Gitea binary.
  file:
    src: "{{ gitea_user_home }}/gitea/gitea"
    dest: "/usr/local/bin/gitea"
    state: link
  notify: restart gitea

- name: Copy Gitea systemd service file into place (for systemd systems).
  template:
    src: gitea.service.j2
    dest: /etc/systemd/system/gitea.service
    owner: root
    group: root
    mode: 0755
  when: "ansible_service_mgr == 'systemd'"

- name: Copy Gitea init script into place.
  template:
    src: "gitea.init-{{ ansible_os_family }}.j2"
    dest: /etc/init.d/gitea
    owner: root
    group: root
    mode: 0755
